fixed a few bugs in slow

diff --git a/bin/slow b/bin/slow
--- a/bin/slow
+++ b/bin/slow
@@ -1,58 +1,59 @@
 #!/bin/bash
 
-DEVICE=$1 # arguments
-TOBURN=$2
+DEVICE=$1 # device getting burned
+TOBURN=$2 # bitstream used to burn
+NUMHRS=$3 # number of hours to burn 
 
-RUNDIR="/home/adam/RO-PUF/runs/"
-ELFDIR=$RUNDIR"bin/characterizer_real.elf"
-CHRDIR=$RUNDIR"bit/inv49Puf.bit"
+RUNDIR="/home/adam/RO-PUF/runs"
+ELFDIR=$RUNDIR"/bin/csv.elf"
+CHRDIR=$RUNDIR"/bit/burnSpace.bit"
 
-if [ -z $DEVICE ] || [ -z $TOBURN ]; then
+DATE=$( date '+%m.%d.%y-%H.%M' ) # date of burn
+LOGSDIR=$RUNDIR"/logs/"$DEVICE"/"$DATE # logs directory
 
-    echo "usage: [ control | burn | test ] [ shorts ] "
-fi
+RED='\033[0;31m'
+CLR='\033[0m'
 
-if [ $TOBURN -lt 0 ] || [ $TOBURN -gt 7 ]; then
 
-    echo "usage: [ control | burn | test ] [ shorts ] "
+re='^[0-9]+$'
+if ! [[ $NUMHRS =~ $re ]];  then
+    echo -e $RED"\terror: must specify a number of iterations"$CLR; exit 1
 fi
 
 if [ $DEVICE = "control" ] || [ $DEVICE = "burn" ] || [ $DEVICE = "test" ]; then
 
-    DATE=$( date '+%m.%d.%y-%H.%M' )
+    # make log directory
+    mkdir -p $LOGSDIR
 
-    for i in {0..3}; do 
+    # initial characterization
+    LOGFILE=$LOGSDIR"/characterization_0.log" 
+    if [ $DEVICE = "test" ]; then
+        echo "characterizing..."
+        char $CHRDIR $ELFDIR |& tee $LOGFILE			 
+    else
+        char $CHRDIR $ELFDIR > $LOGFILE
+    fi
 
-	# make log directory
-	mkdir -p $RUNDIR"logs/"$DEVICE"/"$DATE
+    for (( i=1; i<=$NUMHRS; i++)); do
+
+        # burn for one hour
+        deploy $RUNDIR"/bit/"$TOBURN
+        sleep 4h
 
         # characterize 
-        LOGFILE=$RUNDIR"logs/"$DEVICE"/"$DATE"/characterization_"$i".log" 
+        LOGFILE=$LOGSDIR/"characterization_"$i".log" 
 
 	if [ $DEVICE = "test" ]; then
 	    echo "characterizing..."
-            characterize.exp $CHRDIR $ELFDIR |& tee $LOGFILE			 
+            char $CHRDIR $ELFDIR |& tee $LOGFILE			 
 	else
-	    characterize.exp $CHRDIR $ELFDIR > $LOGFILE
+	    char $CHRDIR $ELFDIR > $LOGFILE
 	fi
-        
-        # burn for one hour
-        burn.exp "/home/adam/RO-PUF/runs/bit/monster_burn.bit"
-        sleep 1h
 
     done
 
-        # characterize again
-        LOGFILE=$RUNDIR"logs/"$DEVICE"/"$DATE"/characterization_"$i".log" 
 
-	if [ $DEVICE = "test" ]; then
-	    echo "characterizing..."
-            characterize.exp $CHRDIR $ELFDIR |& tee $LOGFILE			 
-	else
-	    characterize.exp $CHRDIR $ELFDIR > $LOGFILE
-	fi
-
-    # TODO get rid of annoying  character
+    # TODO get rid of annoying character
 else
     echo "usage: [ control | burn | test ] [ shorts ] "
 fi
